/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBarMenuComponent: typeof import('./src/components/AppBarMenuComponent.vue')['default']
    DrawerComponent: typeof import('./src/components/DrawerComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VAppBarTitle: typeof import('vuetify/lib')['VAppBarTitle']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFadeTransition: typeof import('vuetify/lib')['VFadeTransition']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VOverlay: typeof import('vuetify/lib')['VOverlay']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/lib')['VProgressLinear']
    VRow: typeof import('vuetify/lib')['VRow']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
  }
}
