import MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.2.5',
  date: '2022-01-26T08:40:11.058Z',
};
export default meta;
