import MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.2.9',
  date: '2022-02-11T23:30:14.130Z',
};
export default meta;
