import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.2.12',
  date: '2022-03-09T11:10:48.621Z',
};
export default meta;
